catalog:
  services: # catalog must advertise at least one service
    - id: D11D0A3C-DFA0-11E4-83C4-B11A9580656B
      name: extracttext
      description: >
        The Text Extraction API uses HP KeyView to extract metadata and text
        content from a file that you provide.
      bindable: false
      tags:
        - hp
        - text extraction
        - idol
      metadata:
        displayName: HP IDOL Text Extraction
        imageUrl: https://s3.amazonaws.com/azuqua_static/images/page-channel-hub/icon-hp-idol-ondemand.png
        longDescription: >
          The Text Extraction API uses HP KeyView to extract metadata and text content from a file that you provide.
          The API can handle over 500 different file formats.
        providerDisplayName: HP IDOL OnDemand - Text Extraction
        documentationUrl: http://www.idolondemand.com/developer/apis/extracttext
        supportUrl: https://github.com/Altoros/idol-service-broker
      plans: # a service has one or more plans
        - id: D9212B0A-DFA0-11E4-AAF9-B11A9580656B
          name: try
          description: For test only
          metadata:
            bullets:
              - For test only
            costs:
              - amount:
                  usd: 0.0
                unit: MONTHLY
            displayName: Try

# credentials for Cloud Controller to authenticate with the broker
basic_auth:
  username: admin
  password: password

# credentials for IDOL OnDemand API
idol:
  apikey: a-test-key
