source 'https://rubygems.org'
ruby "2.2.0"

gem 'sinatra'
gem 'rack-flash3'
gem 'cf-app-utils'
gem 'rake'

group :test do
  gem 'minitest'
  gem 'rack-test'
  gem 'rerun'
  gem 'capybara'
  gem 'capybara_minitest_spec'
  gem 'pry'
end
