source 'https://rubygems.org'

gem 'sinatra'
gem 'rack-flash3'
gem 'cf-app-utils'
gem 'rake'
gem 'httparty'

group :test do
  gem 'minitest'
  gem 'rack-test'
  gem 'rerun'
  gem 'capybara'
  gem 'capybara_minitest_spec'
  gem 'pry'
end
